# Generated by Django 4.2.5 on 2023-10-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='footballplayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.IntegerField()),
                ('age', models.IntegerField()),
                ('record', models.IntegerField()),
            ],
        ),
    ]
